### ISSUE TITLE
[Build Issue] - Not building with latest Swift version

### ISSUE THREAD

**Issue by tikimcfee** [codeface-io/LSPService#1]
Heya! I'll be short and sweet: 

First: Thank you for sharing this! Fantastic idea, and I can't wait to try it with my tools.

Second: Darn thing won't build! Seems like a few protocol violations cropped up:

```
LSPService/SourcePackages/checkouts/swift-nio/Sources/NIO/MarkedCircularBuffer.swift:132:1: Type 'MarkedCircularBuffer<Element>' does not conform to protocol 'MutableCollection'
LSPService/SourcePackages/checkouts/swift-nio/Sources/NIO/MarkedCircularBuffer.swift:132:1: Unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
LSPService/SourcePackages/checkouts/swift-nio/Swift.MutableCollection:8:12: 'subscript(_:)' declared here
LSPService/SourcePackages/checkouts/swift-nio/Swift.MutableCollection:6:14: Requirement 'subscript(_:)' declared here
LSPService/SourcePackages/checkouts/swift-nio/Sources/NIO/CircularBuffer.swift:114:1: Type 'CircularBuffer<Element>' does not conform to protocol 'MutableCollection'
LSPService/SourcePackages/checkouts/swift-nio/Sources/NIO/CircularBuffer.swift:114:1: Unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
LSPService/SourcePackages/checkouts/swift-nio/Swift.MutableCollection:8:12: 'subscript(_:)' declared here
LSPService/SourcePackages/checkouts/swift-nio/Swift.MutableCollection:6:14: Requirement 'subscript(_:)' declared here
```

Looks like an NIO dependency mismatch? Might just need a version bump. Happy to help if I can, just let me know!

**Comment by codeface-io** [comment]
Hey there, thanks for raising this issue. On first look, it seems the imported version of NIO isn't up to date with your version of Swift.

I'll look into it further this week, just now I'm quite occupied.

If you see how to solve it, feel free to make a PR. Collaboration is much appreciated! 😊

**Comment by tikimcfee** [comment]
Done deal - https://github.com/flowtoolz/LSPService/pull/2 for your merging pleasure!

**Comment by codeface-io** [comment]
Thanks for the adjustments. I merged your PRs. Feel free to continue giving feedback and ideas.

I'm now getting back into my projects again myself. First thing will be some high level documentation, clearer naming etc. That should make the LSP related stuff more accessible.
