### ISSUE TITLE
python language server (python-lsp-server)

### ISSUE THREAD

**Issue by huppyflup** [codeface-io/LSPService#4]
I tried to use codeface with python.

What I did:
- download and run lspservice
- install python-lsp-server via pip in a virtual environment (venv)
- add the entry to LSPServiceConfig.json
- restart lspservice

lspservice is starting the python lsp correctly when codeface asked it (startup info is printed). Codeface doesn't draw arrows and highlight code so I guess it has some problem.

The Codeface blog sounds like that it is possible to add language servers. I saw to late the comment in this readme "Experiment again with python language servers (and get one to work)" that lets me assume that it isn't working right now or am I doing something wrong?

**Comment by codeface-io** [comment]
Hey @huppyflup,

Thanks for reaching out. You've done nothing wrong 🙂

Every language eco system and every language server implementation is different. Setting up and using LSP servers unfortunately still requires quite intricate knowledge of the respective eco system and server. So I don't know specifics of the Python case.

Generally, I can say this:
* It's often necessary to build a project (or ensure it runs) before analyzing it.
* The server needs to support requests for document symbols and symbol references.
* Some servers require specific arguments or environment variables.
* Some servers deviate in subtle but fatal ways from the LSP standard. I can only iron these out one by one.

So I haven't yet dived into many languages yet. Here's what I experienced so far:
* I have once configured and launched pyls (a Python Language Server) but haven't applied it to a project as I'm not familiar with the eco system.
* I've developed Codeface mainly with the Swift Language Server and documented the details.
* I've seen Java code visualizations from users, so this works in principle.
* Just this week, I made it work with Dart-/Flutter projects. I'll release an update and document the details in the next days.
* I'm currently working on using the Kotlin Language Server, but that's a tricky one it seems.

By gaining experience with multiple different Language Servers I'll get a better picture of the challenges and patterns. Also this will iron out the app and infrastructure, so they'll be able to detect and handle more LSP servers with less need for implementation or documentation.

I know this answer might be dissatisfactory. But so far I'm developing this alone in addition to a full time job, so I can only move this forward one step at a time. The current top priority is certainly the "onboarding" experience and ease of setup 🤞🏻

**Comment by huppyflup** [comment]
hey @flowtoolz, thanks for your answer.

Sadly I also have no knowledge of how this language server exactly handles the LSP.

Sounds like I have to wait 🙂

**Comment by codeface-io** [comment]
> lspservice is starting the python lsp correctly when codeface asked it (startup info is printed).

I assume you're using [this LSP server](https://github.com/python-lsp/python-lsp-server). Can you provide me your config JSON entry and point me to an open-source project to analyze? Then I can quickly narrow down the nature of the issue that you're experiencing :)

**Comment by huppyflup** [comment]
Yes, that's the server.

Config:
```
{
  "python" : {
    "path" : "/Users/<user>/pylsp/.env/bin/pylsp",
    "arguments" : ["-v"],
    "environment" : {}
  }
}
```

You could analyze the lsp server itself or if you want a small project https://github.com/python-lsp/python-lsp-jsonrpc

**Comment by codeface-io** [comment]
On first investigation, it seems this LSP server does not adhere to the LSP standard 🤨

In response to the [document symbols request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol), instead of [document symbols](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol), it sends things like this:

```json
{
    "containerName": null,
    "location": {
        "uri": "file:///Users/seb/Desktop/python-lsp-jsonrpc-develop/pylsp_jsonrpc/dispatchers.py",
        "range": {
            "start": {
                "character": 0,
                "line": 6
            },
            "end": {
                "character": 46,
                "line": 6
            }
        }
    },
    "kind": 13,
    "name": "_RE_FIRST_CAP"
}
```

As you can see, a [correct document symbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol) does not have a `location` but rather directly a `range` and a `selectionRange`.

I'll have to investigate more to find out whether this is somehow (like through capability specification) still part of LSP or whether it's simply a bold quirk of this particular LSP server.

(LSP is a **protocol** and its whole purpose is to **standardize** these things, so apps like Codeface only need to know the protocol ... ah 😖 ... Best case would be that Codeface is actually the party breaking protocol, then I can improve that. Worst case would be that this LSP server "interprets" the protocol and we can only raise a GitHub issue there ...)

**Comment by codeface-io** [comment]
... So the answer is somewhere in the middle: python-lsp-server actually sends [document information](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolInformation) objects instead of document symbols. This behaviour is valid but deprecated.

If we can't bring the authors to modernize python-lsp-server in reasonable time, and if truly no other (better) Python LSP server exists, I will adjust Codeface to handle this deprecated behaviour, because Python is just too important 😊

**Comment by huppyflup** [comment]
It looks like this response is ok.
[document symbols request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol) says the response is one of `SymbolInformation[]` or `DocumentSymbol[]`. SymbolInformation has the location field.

**Comment by codeface-io** [comment]
> It looks like this response is ok.
> [document symbols request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol) says the response is one of `SymbolInformation[]` or `DocumentSymbol[]`. SymbolInformation has the location field.

Yeah, found that too, see my last reply 😊

**Comment by huppyflup** [comment]
oh :sweat_smile:

There is an issue asking to change the behavior https://github.com/python-lsp/python-lsp-server/issues/110 but it is a bit old.

Question would be is it better if LSPService handles it in case other LS respond with SymbolInformation too?

> Python is just too important

That's right :grin:
But don't feel rushed I'm sure you have enough to do.

I opened an issue in python-lsp-server https://github.com/python-lsp/python-lsp-server/issues/396

**Comment by codeface-io** [comment]
Thanks for opening the new issue, although I think it's in the interest of the authors to rather re-inspire the old existing one.

[They have already responded](https://github.com/python-lsp/python-lsp-server/issues/110#issuecomment-1601237095), but until this is released can understandably take a while. In the meantime, I'll check what alternatives there are (jedi-language-server? Pylance?) and then decide ...

**Comment by huppyflup** [comment]
I took a short look on both.

jedi looks good:

Not sure if this is a problem: "Python language server sent message via stdErr".
If I see correctly it sends a DocumentSymbol.
```
{
    "uri": "...", 
    "range": {
        "start": {
            "line": 159, 
            "character": 4
        }, 
        "end": {
            "line": 159, 
            character": 25
        }
    }
}
```
But it isn't working.

I can't find a way install pylance.

**Comment by huppyflup** [comment]
I tried the new codeface version 1.5.7 with jedi-language-server 0.41.1 and it seems to work as expected 😊
thanks

**Comment by codeface-io** [comment]
@huppyflup Oh my, that's great news! 🎉 Thanks for staying on the ball with this!

Is there anything specific you had to do that I should document?

Btw, the documentation is now open-source in the [Codeface repo Wiki](https://github.com/codeface-io/Codeface/wiki/Codeface-Documentation). You could also drop some notes there, so others can follow in your foot steps 😃

**Comment by huppyflup** [comment]
@flowtoolz Done, but don't look at it 🫣

**Comment by codeface-io** [comment]
Ah that's nice! Thanks a lot 🙏🏻

(Warum kommen alle die an Architektur-Visualisierung interessiert sind aus Deutschland? 😂)

**Comment by huppyflup** [comment]
Gute Frage, aber scheinbar gibt es da auch einen Schweizer 🧐
